on:
  pull_request:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  test-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const query = `
              query($number: Int!) {
                repository(owner: "roberts-sandbox", name: "special-bassoon") {
                  pullRequest(number: $number) {
                    headRepositoryOwner {
                      login
                    }
                    maintainerCanModify
                  }
                }
              }
            `;
            console.log(`context.issue.number`, context.issue.number)
            console.log(`context.number`, context.number)
            const pullNumber = context.issue.number;
            const variables = { number: pullNumber };
            try {
              console.log(`Check roberts-sandbox/special-bassoon#${pullNumber} for edit perms ...`);
              const result = await github.graphql(query, variables);
              console.log(JSON.stringify(result, null, 2));
              const pullRequest = result.data.repository.pullRequest;
              if (pullRequest.headRepositoryOwner.login == 'roberts-sandbox') {
                console.log('PR owned by roberts-sandbox');
                return;
              }
              if (!pullRequest.maintainerCanModify) {
                console.log('PR not owned by roberts-sandbox and does not have maintainer edits enabled');
                await github.issues.createComment({
                  issue_number: pullNumber,
                  owner: 'roberts-sandbox',
                  repo: 'special-bassoon',
                  body: "grant perms please!"
                });
              }
            } catch(e) {
              console.log(e);
            }
